---
- name: (Pre-ops) Print the desired list of pkgs to be installed
  ansible.builtin.debug:
    msg: |
     ----------------------------------------------
     The following packages will be installed:

     {% for pkg in install-packages.packages %}
     {{ pkg }}
     {% endfor %}
     ----------------------------------------------
