---
- name: Update package source list
  apt:
    update_cache: yes

- name: Install pre-requisite apk packages
  ansible.builtin.apt:
    pkg:
    - curl
    - runc
    - bridge-utils
    - apt-transport-https

- name: Create a directory to store the CNI binary
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory

- name: Check if containerd is already installed
  shell: "command -v containerd"
  register: is_containerd_installed

- name: Install CNI plugin with official script
  shell: "curl -sSL https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-linux-amd64-v{{ cni_version }}.tgz | sudo tar -xvz -C /opt/cni/bin"
  when: is_containerd_installed.stdout | length == 0

- name: Create a directory to store the Containerd configuration
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
  when: is_containerd_installed.stdout | length == 0

- name: Install Containerd
  ansible.builtin.apt:
    name: containerd
    state: present
  when: is_containerd_installed.stdout | length == 0

- name: Write default configuration to /etc/contained
  command: |
    sudo containerd config default > /etc/containerd/config.toml
  when: is_containerd_installed.stdout | length == 0

- name: Enable contained as a daemon service
  ansible.builtin.service:
    name: containerd
    enabled: yes
    state: started
    daemon_reload: yes
  when: is_containerd_installed.stdout | length == 0

