---
- name: Install Minio Client from the latest release
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/bin/mc
    timeout: 60

- name: Grant executable permission to mc
  ansible.builtin.file:
    path: /usr/bin/mc
    state: file
    mode: a+x

- name: Enable autocompletion
  shell: "mc --autocompletion >/dev/null 2>&1"

- name: Configure minio
  become_user: "{{ ansible_user }}"
  block:
  - name: Create minio default directory
    file:
      path: /home/{{ ansible_user }}/.mc
      state: directory
      owner: "{{ ansible_user }}"
      group: users
      mode: 0755

  - name: Create minio default directory (root)
    become_user: root
    file:
      path: /root/.mc
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Copy minio config file to remote server
    ansible.builtin.template:
      src: config.json.j2
      dest: /home/{{ ansible_user }}/.mc/config.json
      owner: "{{ ansible_user }}"
      group: users
      mode: 0644

  - name: Copy minio config file to remote server
    become_user: root
    ansible.builtin.template:
      src: config.json.j2
      dest: /root/.mc/config.json
      owner: root
      group: root
      mode: 0644
