---
- name: Install Minio Client from the latest release
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/bin/mc
  become: true

- name: Grant executable permission to mc
  ansible.builtin.file:
    path: /usr/bin/mc
    state: file
    mode: a+x
  become: true

- name: Enable autocompletion
  shell: "mc --autocompletion >/dev/null 2>&1"
