---
- name: Decrypt text from file
  hosts: localhost
  become: true
  tasks:
    - name: Decrypt text from vault file
      community.general.ansible_vault:
        decrypt: yes
        src: secret.enc.txt
      register: decrypted_text

    - name: Print decrypted text
      debug:
        msg: "Decrypted text: {{ decrypted_text.stdout }}"
