---
base_packages:
  - linux-headers-generic
  - linux-image-generic
  - curl
  - dnsutils
  - iputils-ping
  - net-tools
  - screen
  - telnet
  - tree
  - vim
  - wget

extra_packeges:
  - neofetch
  - tmux
