---
- name: Stop Proxmox VMs
  hosts: proxmox-server
  become: yes

  roles:
    - role: proxmox.ops/stopvm.ops/
      vars:
        - pm_user: "root@pam"
        - pm_host: "192.168.1.10"
        - pm_node: "pve"
        - target_vm_group: "NAS"
        # vm operations will be executed in the index order
        - target_vms: [560]
