---
- name: Power cycle remote control
  block:
  - name: Verify power state
    when: check_status
    block:
    - name: Check current power state
      command: "ipmitool -H {{ remote_server_ip }} -U ADMIN -P {{ admin_password }} -I lanplus power status"
      register: pre_check_result

  - name: Power on the remote server
    command: "ipmitool -H {{ remote_server_ip }} -U ADMIN -P {{ admin_password }} -I lanplus power on"
    when: "('off' in pre_check_result.stdout) and (power == 'on')"
    register: power_on_result

  - name: Power off the remote server
    command: "ipmitool -H {{ remote_server_ip }} -U ADMIN -P {{ admin_password }} -I lanplus power off"
    when: "('on' in pre_check_result.stdout) and (power == 'off')"
    register: power_off_result

  - name: Check if previous operation is functional
    debug:
      msg: "Updating power state... It may take a few minutes, please wait."
    when: (power_on_result.stdout is defined) or (power_off_result.stdout is defined)

  - name: Verify power state
    when:
      - check_status
      - (power_on_result.stdout is not defined) and (power_off_result.stdout is not defined)
    block:
    - name: Check current power state
      command: "ipmitool -H {{ remote_server_ip }} -U ADMIN -P {{ admin_password }} -I lanplus power status"
      register: result

    - name: Print result
      debug:
        msg: "{{ result.stdout }}"
