---
proxmox-ubuntu-privileged-standard-lxc:
  hosts:
    proxmox-node:
      ansible_host: 192.168.1.10

    lxc-node:
      ansible_host: 192.168.1.100

    localhost:
      ansible_connection: local

  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
