---
- name: Install rootless Containerd (Full)
  block:
    - name: Update package source list
      apt:
        update_cache: yes

    - name: Install pre-requisite apk packages
      ansible.builtin.apt:
        pkg:
        - curl
        - runc
        - bridge-utils
        - uidmap
        - apt-transport-https

    - name: Assign subuids and subgids to the target user
      shell: "usermod --add-subuids 100000-165535 --add-subgids 100000-165535 {{ ansible_user }}"

    - name: Install Nerdctl, CNI, and Containerd (Full) with official script
      shell: "curl -sSL https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version }}/nerdctl-full-{{ nerdctl_version }}-linux-amd64.tar.gz | sudo tar -xvz -C /usr/local"
      args:
        warn: false

    - name: Setup rootless Containerd for the target user
      shell: "containerd-rootless-setuptool.sh install"
      become: true
      become_user: "{{ ansible_user }}"

    - name: Install Buildkitd with setuptool
      shell: "containerd-rootless-setuptool.sh install-buildkit"
      become: true
      become_user: "{{ ansible_user }}"

    - name: Enable Contained as a daemon service
      ansible.builtin.service:
        name: containerd
        enabled: yes
        state: started
        daemon_reload: yes
