---
- name: Make sure the wheel group exists
  group:
    name: wheel
    state: present

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  user:
    name: "{{ username }}"
    groups:
    - wheel
    - sudo
    append: yes
    shell: /bin/bash
    state: present
    createhome: yes

- name: Set up authorized keys for the new user
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  loop: "{{ public_keys }}"
