---
- name: Update package source list
  apt:
    update_cache: yes

- name: Install packages defined in the list
  ansible.builtin.apt:
    pkg: "{{ packages }}"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
