---
- name: Update package source list
  apt:
    update_cache: yes

- name: Install base packages defined in the list
  ansible.builtin.apt:
    pkg: "{{ install_packages.packages }}"

- name: Install user-defined extra packages
  ansible.builtin.apt:
    pkg: "{{ extra_packages }}"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
