---
- name: (Post-ops) Get VM(s) current state
  community.general.proxmox_kvm:
    vmid: "{{ item }}"
    api_user: "{{ pm_user }}"
    api_password: "{{ lookup('env','PM_PASS') }}"
    api_host: "{{ pm_host }}"
    node: "{{ pm_node }}"
    state: current
  loop: "{{ target_vms }}"
