---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  annotations:
    effect: "deny all traffic by default"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
