---
- name: Purge Proxmox LXC Container
  hosts: proxmox-02
  become: yes

  vars_files:
    - ../../../../vars/lxc/unprivileged/bake-proxmox-ubuntu-standard-lxc.yml
  roles:
    - role: lxc.ops/remove.ops/
