---
- name: Setup Minio Connection
  hosts: all
  become: yes

  vars:
    - home_user: "packer"
    - minio_remote_url: "http://10.178.0.9:9000"
    - minio_access_key: "{{ lookup('env','MINIO_ACCESS_KEY') }}"
    - minio_secret_key: "{{ lookup('env','MINIO_SECRET_KEY') }}"
  roles:
    - role: minio.ops/setup.ops/
