---
- name: Backup Data to Minio
  hosts: all
  become: yes

  vars:
    - remote_server: "http://10.178.0.9:9000"
  roles:
    - role: ../../roles/minio.ops/setup.ops/
    - role: ../../roles/minio.ops/backup.ops/
