# /deploy/apps/staging/nginx-example/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
commonLabels:
  env: staging
  project: nginx-example
  app: nginx-example
namePrefix: staging-
resources:
  - ../../base/nginx-example/ # base resources
patches:
  - deployment.yaml
images:
  - name: nginx
    newTag: latest
