---
- name: Install Docker with script
  shell: "wget -qO- https://get.docker.com/ | sh"
  register: installation_result
  args:
    warn: false
  become: yes

- name: Enable docker to start at boot
  ansible.builtin.service:
    name: docker
    enabled: yes
  when: installation_result.rc == 0
  become: yes

- name: Add user {{ user.name }} to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: yes
  when: installation_result.rc == 0
  become: yes

- name: "Post installation message"
  debug:
    msg: Use "newgrp docker" to use the group immediately
