---
# build vars
vm_id: 9001
vm_disk_size: "10G"

host_config: "vars/host.pkvars.hcl"
vm_config: "vars/debian-12.pkrvars.hcl"
playbook_file: "playbooks/debian_12_server.yml"
packer_template: "debian-proxmox-packer-template.pkr.hcl"
template_name: "prod-debian-12-server-template"

