---
apiVersion: audit.k8s.io/v1
kind: Policy
omitStages: ["RequestReceived"]
rules:
  - namespace: ["prod-namespace"]
    verb: ["delete"]
    resources:
      - groups: ""
        resources: ["pods"]
        resourceNames: ["nginx-pod"]
    level: RequestResponse
  - resources:
      - groups: ""
        resources: ["secrets"]
    level: Metadata
