---
- name: Download packer release
  get_url:
    url: "{{ packer_release_url }}"
    dest: "/tmp/{{ packer_release_filename }}"
    force: yes # overwrite existing files

- name: Unzip packer binary from release
  unarchive:
    src: "/tmp/{{ packer_release_filename }}"
    dest: "/tmp"

- name: Make packer executable
  file:
    src: "/tmp/packer"
    dest: "{{ packer_install_path }}/packer"
    mode: a+x
    state: move
