---
# Bake ubuntu-2204-server

- name: "Proxmox Ubuntu 2204 Server"
  hosts: localhost
  become: yes

  vars_files:
    - ./vars/ansible-vars/apt.yml
    - ./vars/ansible-vars/docker.yml

  roles:
  - role: ./roles/apt.ops/set-sources.ops/
    vars:
      release: "jammy"
  - role: ./roles/apt.ops/install-packages.ops/

  - role: ./roles/maintenance.ops/key.ops/
    vars:
      key:
        public_keys:
        - ~/.ssh/id_rsa_yubikey.pub

  - role: ./roles/minio.ops/
    vars:
      remote_server: "http://10.178.0.9:9000"
      minio_access_key: "{{ lookup('env','MINIO_ACCESS_KEY')}}"
      minio_secret_key: "{{ lookup('env','MINIO_SECRET_KEY')}}"

  - role: ./roles/docker.ops/

  - role: ./roles/proxmox.bootstrap/
