---
# Bake cn-ubuntu-2204-server

- name: "Bake proxmox cn ubuntu 22.04 server"
  hosts: localhost
  become: yes

  vars_files:
    - ./vars/apt.yml
    - ./vars/maintenance.yml

  roles:
  - role: ./roles/apt.ops/set-sources.ops/
    vars:
      release: "jammy"
  - role: ./roles/apt.ops/install-packages.ops/
    vars:
      extra_packages:
      - neofetch

  - role: ./roles/maintenance.ops/key.ops/

  - role: ./roles/proxmox.bootstrap/
