---
# Bake cn-ubuntu-2204-server

- name: "Bake proxmox cn ubuntu 22.04.1 server"
  hosts: localhost
  become: yes

  vars_files:
    - ./vars/apt.yml
    - ./vars/maintenance.yml

  roles:
  - role: apt.ops/set-sources.ops/
    vars:
      release: "jammy"
  - role: apt.ops/install-packages.ops/
    vars:
      extra_packages:
      - neofetch
  - role: maintenance.ops/key.ops/
  - role: proxmox.packer.vm.ops/bootstrap.ops/
