---
# Bake cn-ubuntu-2204-server

- name: "Bake proxmox cn-ubuntu-22.04-server"
  hosts: localhost
  become: yes

  vars_files:
    - ./vars/apt.yml
    - ./vars/keys.yml

  roles:
  - role: roles/apt.ops/set-sources.ops/
    vars:
      os: "ubuntu"
      release: "jammy"
      primary_source_uri: "https://mirrors.ustc.edu.cn/ubuntu"
      security_source_uri: "https://mirrors.ustc.edu.cn/ubuntu"
  - role: roles/apt.ops/install-packages.ops/
    vars:
      extra_packages:
      - neofetch
  - role: roles/maintenance.ops/key.ops/
  - role: roles/proxmox.packer.vm.ops/bootstrap.ops/
