---
# Bake containerd-ubuntu-2204-server

- name: "Bake proxmox ubuntu 2204 server (with containerd)"
  hosts: localhost
  become: yes

  vars_files:
    - ./vars/apt.yml
    - ./vars/containerd.yml
    - ./vars/keys.yml

  roles:
  - role: roles/apt.ops/update.ops/
  - role: roles/apt.ops/install-packages.ops/
    vars:
      extra_packages:
      - neofetch
  - role: roles/maintenance.ops/key.ops/
  - role: roles/containerd.ops/
  - role: roles/proxmox.packer.vm.ops/bootstrap.ops/
