---
# Bake docker-ubuntu-2204-server

- name: "proxmox ubuntu 2204 server (with docker)"
  hosts: localhost
  become: yes

  vars_files:
    - ./vars/apt.yml
    - ./vars/docker.yml
    - ./vars/maintenance.yml

  roles:
  - role: apt.ops/update.ops/
  - role: apt.ops/install-packages.ops/
    vars:
      extra_packages:
      - neofetch
  - role: maintenance.ops/key.ops/
  - role: docker.ops/
  - role: proxmox.packer.vm.ops/bootstrap.ops/
