---
# Bake docker-ubuntu-2204-server

- name: "proxmox ubuntu-2204-server (with docker)"
  hosts: localhost
  become: yes

  vars_files:
    - ./vars/apt.yml
    - ./vars/docker.yml
    - ./vars/keys.yml

  roles:
  - role: roles/apt.ops/update.ops/
  - role: roles/apt.ops/install-packages.ops/
    vars:
      extra_packages:
      - neofetch
  - role: roles/maintenance.ops/key.ops/
  - role: roles/docker.ops/
  - role: roles/proxmox.packer.vm.ops/bootstrap.ops/
