---
# Bake ubuntu-2204-server

- name: "Proxmox Ubuntu 2204 Server"
  hosts: localhost
  become: yes

  vars_files:
    - ./vars/apt.yml

  roles:
  - role: ./roles/apt.ops/update.ops/
  - role: ./roles/apt.ops/install-packages.ops/

  - role: ./roles/maintenance.ops/key.ops/
    vars:
      key:
        public_keys:
        - ~/.ssh/id_rsa_yubikey.pub

  - role: ./roles/proxmox.bootstrap/
