---
- name: Disable PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  become: yes

- name: Disable PermitRootLogin
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(#\s*)?PermitRootLogin '
    line: "PermitRootLogin no"
  become: yes

- name: Restart openssh server
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: yes
