---
- name: Perform Containerd Installation
  hosts: all
  become: yes

  vars_files:
    - ./roles/container.ops/containerd.ops/vars/main.yml
  roles:
    # change apt source (optional)
    - role: ./roles/apt.ops/set-sources.ops/
      vars:
      - primary_source_uri: "https://mirrors.ustc.edu.cn/ubuntu/"
      - security_source_uri: "https://mirrors.ustc.edu.cn/ubuntu/"
      - release: "jammy"
    - role: ./roles/container.ops/containerd.ops
      # default installation (rootful mode)
      # vars:
      #   - rootless_containerd: false
      # uncomment the following lines if you wish to configure rootless containerd
      vars:
        - rootless_containerd: true
        - rootless_user: "packer" # target rootless user to run containerd with rootless previledge

