---
- name: Setup Minio Connection
  hosts: all
  become: yes

  vars_files:
    - ./roles/maintenance.ops/proxmox.ops/startvm.ops/variables/main.yml
  roles:
    - role: ./roles/maintenance.ops/proxmox.ops/startvm.ops/
